### ISSUE TITLE
Other Improvements

### ISSUE THREAD

**Issue by Nesze** [Financial-Times/factset-reader#2]
- circleci integration
  https://github.com/Financial-Times/factset-reader/blob/master/app.go#L131
- handle "false" case first, return
- handle success case afterwards ->  reduces indentation for a lot of code
- can that switch statement be handled by a map for example?
- run gometalinter on the project
- run goimports

**Comment by danielcopaciu** [comment]
Done https://github.com/Financial-Times/factset-reader/pull/3
